#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : freezegun
Version  : 0.3.10
Release  : 1
URL      : https://files.pythonhosted.org/packages/1d/3c/fd18e8fdb662370baedae516df1b20aec9c98a6fcf5d93ff8334835552d7/freezegun-0.3.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/1d/3c/fd18e8fdb662370baedae516df1b20aec9c98a6fcf5d93ff8334835552d7/freezegun-0.3.10.tar.gz
Summary  : Let your Python tests travel through time
Group    : Development/Tools
License  : Apache-2.0
Requires: freezegun-python3
Requires: freezegun-python
Requires: python-dateutil
Requires: six
BuildRequires : buildreq-distutils3

%description
FreezeGun: Let your Python tests travel through time
====================================================

%package python
Summary: python components for the freezegun package.
Group: Default
Requires: freezegun-python3

%description python
python components for the freezegun package.


%package python3
Summary: python3 components for the freezegun package.
Group: Default
Requires: python3-core

%description python3
python3 components for the freezegun package.


%prep
%setup -q -n freezegun-0.3.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536549897
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
