#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : freezegun
Version  : 0.3.15
Release  : 11
URL      : https://files.pythonhosted.org/packages/67/eb/6ac50b9faaa5dc2345ed4e905d242b840750d99a15763a880c4d785974e9/freezegun-0.3.15.tar.gz
Source0  : https://files.pythonhosted.org/packages/67/eb/6ac50b9faaa5dc2345ed4e905d242b840750d99a15763a880c4d785974e9/freezegun-0.3.15.tar.gz
Summary  : Let your Python tests travel through time
Group    : Development/Tools
License  : Apache-2.0
Requires: freezegun-license = %{version}-%{release}
Requires: freezegun-python = %{version}-%{release}
Requires: freezegun-python3 = %{version}-%{release}
Requires: python-dateutil
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : python-dateutil
BuildRequires : six

%description
FreezeGun: Let your Python tests travel through time
====================================================

%package license
Summary: license components for the freezegun package.
Group: Default

%description license
license components for the freezegun package.


%package python
Summary: python components for the freezegun package.
Group: Default
Requires: freezegun-python3 = %{version}-%{release}

%description python
python components for the freezegun package.


%package python3
Summary: python3 components for the freezegun package.
Group: Default
Requires: python3-core

%description python3
python3 components for the freezegun package.


%prep
%setup -q -n freezegun-0.3.15
cd %{_builddir}/freezegun-0.3.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582039709
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/freezegun
cp %{_builddir}/freezegun-0.3.15/LICENSE %{buildroot}/usr/share/package-licenses/freezegun/83ff4be984d95e17546d5eaa6e14beba8ef4b5e9
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/freezegun/83ff4be984d95e17546d5eaa6e14beba8ef4b5e9

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
